[FileSettings]
    FileName = "/Users/henryisrael/T2K/regeneration_times_project/inputs/markov_chains/oscpar_only_datafit.root"
    ChainName = "osc_posteriors"
    ParameterNames = ["theta23", "theta13", "dm23", "dm12", "dcp"]
    LabelName = "LogL"

