FileSettings:
    FileName : "/users/php20hti/php20hti/public/chains/all_par_chain_without_adaption.root"
    # FileName : "/users/php20hti/t2ksft/regeneration_times_project/inputs/markov_chains/oscpar_only_datafit.root"
    ChainName : "posteriors"
    # ChainName : "osc_posteriors"
    Verbose : False
    # Model Settings
    MakeMLModel: True

ParameterSettings:
    ParameterNames : ["sin2th","delm2", "delta", "xsec", "sk", "nd"]
    # ParameterNames : ["d", "th"]
    LabelName : "LogL"
    IgnoredParameters : ["LogL_systematic_xsec_cov", "Log", "LogL_systematic_nddet_cov", ]
    ParameterCuts : ["step>10000"] #["LogL<12345678", "step>10000"]


MLSettings:

    FitterPackage : "SciKit"
    FitterName : "histboost"
    TestSize : 0.9

    FitterKwargs:
        max_iter: 10000
        
    MLOutputName: "tf_model_full.pkl"
